### ISSUE TITLE
Add instructions how to build, run and contribute to project

### ISSUE THREAD

**Issue by NiklasMerz** [MarshMello0/VTOLVR-Multiplayer#4]
Hi there,

Nice project. I would like to learn more about this mod. I know nothing about C#, but some other programming languages.

I cloned the repository, added the dependencies and tried to build it with VS2019. But I got some errors for HarmonyLib:

<details>
C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Multiplayer.cs(9,7,9,17): error CS0246: Der Typ- oder Namespacename "HarmonyLib" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Receiver.cs(7,7,7,17): error CS0246: Der Typ- oder Namespacename "HarmonyLib" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Sender.cs(7,7,7,17): error CS0246: Der Typ- oder Namespacename "HarmonyLib" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_LoadingSceneController.cs(7,7,7,17): error CS0246: Der Typ- oder Namespacename "HarmonyLib" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_VTMapManager.cs(7,7,7,17): error CS0246: Der Typ- oder Namespacename "HarmonyLib" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_VTTMapTrees.cs(1,7,1,17): error CS0246: Der Typ- oder Namespacename "HarmonyLib" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Sender.cs(20,13,20,21): error CS0246: Der Typ- oder Namespacename "Traverse" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Receiver.cs(20,13,20,21): error CS0246: Der Typ- oder Namespacename "Traverse" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_LoadingSceneController.cs(49,2,49,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatchAttribute" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_LoadingSceneController.cs(49,2,49,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatch" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Receiver.cs(189,2,189,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatchAttribute" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Receiver.cs(189,2,189,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatch" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Receiver.cs(190,2,190,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatchAttribute" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Networkers\PlaneNetworker_Receiver.cs(190,2,190,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatch" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_LoadingSceneController.cs(52,6,52,19): error CS0246: Der Typ- oder Namespacename "HarmonyPrefixAttribute" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_LoadingSceneController.cs(52,6,52,19): error CS0246: Der Typ- oder Namespacename "HarmonyPrefix" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_VTTMapTrees.cs(3,2,3,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatchAttribute" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_VTTMapTrees.cs(3,2,3,14): error CS0246: Der Typ- oder Namespacename "HarmonyPatch" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_VTTMapTrees.cs(6,6,6,19): error CS0246: Der Typ- oder Namespacename "HarmonyPrefixAttribute" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
1>C:\Users\Niklas\source\repos\VTOLVR-Multiplayer\VTOLVR-Multiplayer\Patches\Patch_VTTMapTrees.cs(6,6,6,19): error CS0246: Der Typ- oder Namespacename "HarmonyPrefix" wurde nicht gefunden (möglicherweise fehlt eine using-Direktive oder ein Assemblyverweis).
========== Erstellen: 0 erfolgreich, 1 fehlerhaft, 0 aktuell, 0 übersprungen ==========
</details>

My dependencies folder looks like this:

```
Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       06.03.2020     15:13                .vs
-a----       08.08.2018     19:28         114176 0Harmony.dll
-a----       05.03.2020     18:05         373248 Assembly-CSharp-firstpass.dll
-a----       05.03.2020     18:05        3963392 Assembly-CSharp.dll
-a----       05.03.2020     18:16            302 instructions.txt
-a----       15.02.2020     15:13          68096 ModLoader.dll
-a----       05.03.2020     18:05         331776 Unity.TextMeshPro.dll
-a----       22.06.2019     17:57          77312 UnityEngine.AudioModule.dll
-a----       22.06.2019     17:57         917504 UnityEngine.CoreModule.dll
-a----       22.06.2019     17:58          77824 UnityEngine.dll
-a----       22.06.2019     17:58          87552 UnityEngine.PhysicsModule.dll
-a----       22.06.2019     17:58          26624 UnityEngine.TextRenderingModule.dll
-a----       22.06.2019     17:58         258048 UnityEngine.UI.dll
```

I tried some fixes from intellisense and got to build a Multiplayer.dll with no idea if it works. 

**How do I run this mod?** With Modloader? How do players connect? 

Can I help with documentation or coding? I would love to learn more about the current state of the mod.

Looking forward.

**Comment by NiklasMerz** [comment]
Update. With some code modifcations, I got the mod to load in the mod loader

**Comment by MarshMello0** [comment]
Hi @NiklasMerz 

Thank you for your interest! Sorry, you've caught this at an awkward point of upgrading in dependencies. 
The multiplayer mod now uses [Harmony 2.0](https://github.com/pardeike/Harmony) whereas the mod loader still uses Harmony 1.2. So currently it requires a bit of extra work that what was stated in the Readme.

### Updating the mod loader to the new harmony
Clone the [dev branch](https://github.com/MarshMello0/VTOLVR-ModLoader/tree/dev) of the mod loader repo 

Download the latest version of harmony, place it in `dll` folder and `VTOL VR\VTOLVR_Data\Managed`

Place the other required dlls in the `dll` folder.

### Updating the multiplayer mod to the new harmony

Just place the new 2.0 version of harmony into the `Dependencies` folder and building it in debug mode should be fine now.

#### Remember to press no to any updates!!! (It will downgrade the harmony in the managed folder)

> How do I run this mod? With Modloader? How do players connect?

You build it and place it in your mods folder. 
Load the mod from the custom in-game UI.
Then an MP button should show at the bottom right of a scenario.
_0.0.15 just came out two days ago and may of broken that mp button_

> Can I help with documentation or coding? I would love to learn more about the current state of the mod.

Yes! I would love any help with both. If you're in the [modding discord](https://discord.gg/XZeeafp) just ask away in #modding-help or DM me `. Marsh.Mello .#0001`.

**Comment by NiklasMerz** [comment]
Thanks for the instructions. I will go into this soon when a friend is ready to test this with me.

**Comment by NiklasMerz** [comment]
Can I test the multiplayer somehow alone? Looks like we had some issues trying it with two people.

**Comment by MarshMello0** [comment]
You can host a lobby by your self if the issue was getting into the game. But there is a work in progress solo testing mechanic. 

In Multiplayer.cs Line 18 `public static bool SoloTesting = true;` is what is used for solo testing. It's still set to true, so that could of been the issue.

Positions and vehicle movement updates in that solo test, missiles are currently being worked on.
